#!/usr/bin/env bash
# Transferring a file from client to a server
if [ "$4" -eq '' ]
then
	scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~/
else
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
