#!/usr/bin/env bash
# Installing nginx on our webserver
sudo apt-get -y update
sudon apt-get -y install nginx
echo "Holberton School makes learning fun." > /var/www/html/index.html
service nginx restart
