#!/usr/bin/env bash
#last one
sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
sudo sed -i "s/#error_page 404/error_page 404/" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html
sudo service nginx restart
