#!/usr/bin/env bash
# redirection /redirect_me
sudo apt-get update
sudo apt-get -y install nginx
echo 'Holberton School' > /var/www/html/index.html
sed -i '/server_name _/a location /redirect_me { rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4? permanent; }' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /usr/var/www/error/404.html
error_replace="#error_page"
error_string="error_page"
sed -i "s/$error_replace/$error_string/\n" /etc/nginx/sites-available/default
service nginx restart
