#!/usr/bin/env bash
# this scrip displays username, user id and home directory
# of the  /etc/passwd.

filename="/etc/passwd"
while IFS= read -r username userid homedir
do
	echo "$username $userid $homedir" | cut -d: -f 1,3,6
done < $filename
