#!/usr/bin/env bash
#a script print time 10 else string and more conditions in a bucle
n=1
while [ "$n" -le 10 ]
do
	if [ $n == 4 ]
	then
		echo "bad luck"
	elif [ $n == 8 ]
	then
		echo "good luck"
	else
		echo "Holberton School"
	fi
	((n++))
done
