#!/usr/bin/env bash
#a Bash script that displays the time for 12 hours and 59 minutes.
hour=0
while [ "$hour" -le 12 ]
do
	echo "Hour: $hour"
	min=1
	while [ "$min" -le 59 ]
	do
		echo "$min"
		((min++))
	done
	((hour++))
done
